recipe: default.v1
language: id

pipeline:
- name: WhitespaceTokenizer
  intent_tokenization_flag: true
  intent_split_symbol: "+"
- name: RegexFeaturizer
  case_sensitive: false
  use_lookup_tables: false
  use_regexes: true
  use_word_boundaries: True
  pattern: "[a-f0-9]{32}"
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4

- name: DIETClassifier
  epochs: 200
  constrain_similarities: true

# - name: DIETClassifier
#   epochs: 100
#   drop_rate: 0.4
#   drop_rate_attention: 0.1
#   use_sparse_input_dropout: true
#   use_dense_input_dropout: true
#   batch_size: [32, 128]
#   learning_rate: 0.0005
#   random_seed: 42
#   evaluate_every_number_of_epochs: 10
#   constrain_similarities: True


- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 200
- name: FallbackClassifier
  threshold: 0.3

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 200
- name: TEDPolicy
  max_history: 10
  epochs: 200
assistant_id: 20250709-082057-nullary-nucleus
